---
- hosts: dnsmaster
  roles:
    - dnsmaster

- hosts: dnsclient
  roles:
    - dnsclient

- hosts: local
  tasks:
  - name: Setting DNS
    become: true
    lineinfile:
      dest: "/etc/resolv.conf"
      regexp: "^nameserver"
      line: "nameserver {{ groups['dnsmaster']|first }}"
