---
- name: Installing BIND
  become: true
  yum:
    name: bind
    state: present

- name: Configure BIND
  become: true
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0640
  notify: restart dns

- name: Configure zone mkdev
  become: true
  template:
    src: mkdev.zone.j2
    dest: /var/named/dynamic/mkdev.zone
    owner: named
    group: named
    mode: 0640
  notify: restart dns

- name: Configure keys
  become: true
  template:
    src: dnsclient.conf.j2
    dest: /etc/named/dnsclient.conf
    owner: root
    group: named
    mode: 0640
  notify: restart dns

- name: Rule for firewall
  become: true
  firewalld:
    service: dns
    permanent: true
    immediate: true
    state: enabled
