---
- name: Installing BIND
  become: true
  yum:
    name: bind
    state: present

- name: Configure BIND
  become: true
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0640
  notify: restart dns

- name: Configure zone mkdev
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: named
    group: named
    mode: 0640
  notify: restart dns
  with_items:
    - src: mkdev.zone.j2
      dest: /var/named/dynamic/mkdev.zone
    - src: 90.168.192.in-addr.arpa.j2
      dest: /var/named/dynamic/90.168.192.in-addr.arpa

- name: Configure keys
  become: true
  template:
    src: dnsclient.conf.j2
    dest: /etc/named/dnsclient.conf
    owner: root
    group: named
    mode: 0640
  notify: restart dns

- name: Rule for firewall
  become: true
  firewalld:
    service: dns
    permanent: true
    immediate: true
    state: enabled
